/* eslint-disable no-unused-vars */
enum iconStyles {
  password = 'password',
  email = 'email',
  logoCat = 'logo-cat',
  search = 'search',
  user = 'user',
  time = 'time',
  checkOutline = 'check-outline',
  check = 'check',
  likeOutline = 'like-outline',
  like = 'like',
  home = 'home',
  noActivity = 'no-activity',
  dateFrom = 'date-from',
  dateTo = 'date-to',
  people = 'people',
  peopleOutline = 'people-outline',
  reply = 'reply',
  commentOutline = 'comment-outline',
  commentSingle = 'comment-single',
  comment = 'comment',
  send = 'send',
  cross = 'cross',
  pastOutline = 'past-outline',
  past = 'past',
  infoOutline = 'info-outline',
  info = 'info',
}

export default iconStyles;
